/var/www/html/logs/*.log {
    size 10M
    rotate 7
    maxage 14
    compress
    delaycompress
    missingok
    notifempty
    copytruncate
    su root www-data
}

/var/log/apache2/*.log {
    size 10M
    rotate 7
    maxage 14
    compress
    delaycompress
    missingok
    notifempty
    copytruncate
    su root adm
}
